---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: ms-auth
  namespace: company-mss
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-auth
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: ms-auth
  service:
    name: ms-auth
    port: 80
    targetPort: 8080
    portDiscovery: true
#    gateways:
#    - ms-auth
#    hosts:
#    - ms-auth.company.com
  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 60
    stepWeight: 20
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m
    - name: latency
      templateRef:
        name: latency
      thresholdRange:
        max: 1000
      interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.istio-system/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://ms-auth-canary.company-mss:80/"

---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: latency
  namespace: company-mss
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    histogram_quantile(
        0.99,
        sum(
            rate(
                istio_request_duration_milliseconds_bucket{
                    reporter="destination",
                    destination_workload_namespace="{{ namespace }}",
                    destination_workload=~"{{ target }}"
                }[{{ interval }}]
            )
        ) by (le)
    )
