---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-storage
  namespace: company-mss
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: ms-auth-db
    chart: ms-auth-db-5.3.0
    heritage: Tiller
    release: ms-auth
  name: ms-auth-db
  namespace: company-mss
spec:
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-hostpath-storage
  volumeName: ms-auth-db-pv
  resources:
    requests:
      storage: "8Gi"
