---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth-db
  namespace: company-mss
  labels:
    app: ms-auth-db
    chart: ms-auth-db-5.3.0
    release: "ms-auth"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: ms-auth-db
    release: "ms-auth"
